openapi: 3.0.0
info:
  title: Yurtle API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /tasks:
    post:
      summary: Get All My Tasks
      operationId: post-user
      responses:
        '201':
          description: Task Created
          content:
            application/json:
              schema:
                $ref: ../models/Task.yaml
              examples: {}
        '400':
          description: Missing Required Parameters
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                deadline:
                  type:
                    - string
                    - 'null'
                  format: date
              required:
                - name
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
    parameters: []
    get:
      summary: ''
      operationId: get-tasks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: ../models/Task.yaml
                  total_count:
                    type: number
                required:
                  - tasks
                  - total_count
      description: Fetch all my tasks
  '/tasks/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: UUID
    get:
      summary: Get Task
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: ../models/Task.yaml
              examples: {}
        '404':
          description: Not Found
      operationId: get-task
      description: Retrieve the information of the task with the matching task ID.
    patch:
      summary: Update User Information
      operationId: patch-task
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: ../models/Task.yaml
              examples: {}
        '404':
          description: Not Found
      description: Update the information of an existing task.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                deadline:
                  type:
                    - string
                    - 'null'
                  format: date
            examples: {}
        description: Patch user properties to update.
  '/tasks/{id}/complete':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: UUID
    post:
      summary: Complete Task
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Task.yaml
        '404':
          description: Not Found
      operationId: complete-task
      requestBody:
        content:
          application/json:
            schema:
              type: object
      description: Complete task
components:
  schemas: {}
